services:
  mysql:
    image: mysql:8.0
    container_name: brudam-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: brudam_test
    ports:
      - "3306:3306"
    volumes:
      - brudam_mysql_data:/var/lib/mysql

volumes:
  brudam_mysql_data: